### PR TITLE
fix: align Amendments page On(tx) column to the left.

### PR DESCRIPTION
**Pull request by pdp2121**
## High Level Overview of Change

Align On(tx) column on Amendments table to the left to be consistent with other columns and ensure content are lined up.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Translation Updates
- [ ] Release

### Before

Screenshot 2024-01-25 at 3 39 44 PM

### After
Screenshot 2024-01-25 at 3 40 20 PM

### CODE REVIEW

**Review by ckniffen — APPROVED** [review]

**Comment by ckniffen** [comment]
Does this also look good on mobile?

**Comment by mvadari** [comment]
While you're on this page, can you please increase the font size a bit?

**Comment by pdp2121** [comment]
> Does this also look good on mobile?
@ckniffen 
Mobile view:
Screenshot 2024-01-25 at 3 46 28 PM

**Comment by pdp2121** [comment]
> While you're on this page, can you please increase the font size a bit?

@mvadari we are using the same font size as other tables (Validators & Nodes). I think we want consistency as we have discussed this before

**Review by justinr1234 — APPROVED** [review]

**Comment by mvadari** [comment]
> > While you're on this page, can you please increase the font size a bit?
> 
> @mvadari we are using the same font size as other tables (Validators & Nodes). I think we want consistency as we have discussed this before

The data is a lot more dense on those tables so the small font feels more justified. As a user, the font on the amendments page legitimately feels too small, since there's a lot less data in the table.

**Pull request merged**
