### PR TITLE
fix count on validator page, esp important around activation time.

### PR DESCRIPTION
**Pull request by shortthefomo**
## High Level Overview of Change

Fix bug on count of validators, the current implementation uses length and not length -1
### Type of Change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Translation Updates
- [ ] Release

### TypeScript/Hooks Update

- [ ] Updated files to React Hooks
- [ ] Updated files to TypeScript

### CODE REVIEW

**Comment by mvadari** [comment]
Why should it use `length - 1`?

**Comment by shortthefomo** [comment]
> Why should it use `length - 1`?

length of 
`const array = ['0'] ` 
`array.length = 1 not 0 `

**Comment by shortthefomo** [comment]
wait your right this is wrong.

**Comment by mvadari** [comment]
In case additional proof is needed - 29 valid validators, with length 29 (sorted so you can check for duplicates easily):
image

**Pull request closed without merging**
