### PR TITLE
Add Destination field to NFTokenCreateOffer if exists

### PR DESCRIPTION
**Pull request by shawnxie999**
### Context of Change
Its useful to show the Destination on sell offer if it is in raw data

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### TypeScript/Hooks Update

- [ ] Updated files to React Hooks
- [ ] Updated files to TypeScript

## Before / After
Before 
image

After
image

### CODE REVIEW

**Review by ckniffen — APPROVED** [review]
Killer

**Review by mvadari — APPROVED** [review]

**Comment by ledhed2222** [comment]
What about buy offer?

**Comment by ckniffen** [comment]
> What about buy offer?

This should work on both but worth looking into.

**Comment by shawnxie999** [comment]
> What about buy offer?

Just curious how does it apply to buy offer? I thought it only makes sense for a sell offer where the seller only wants a specific account to buy the nft only

**Comment by ledhed2222** [comment]
That was previously true, but a robust use of brokered mode requires use of
destination on both buy and sell offers where the destination in both cases
is the broker. Otherwise the seller can select whichever buy offer they
want and stiff the broker out of any fees.

**Pull request merged**
