### PR TITLE
fix: display issuer in TrustSet amount

### PR DESCRIPTION
**Pull request by mvadari**
## High Level Overview of Change

Title says it all.

### Context of Change

Noticed while debugging something else

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### TypeScript/Hooks Update

N/A

## Before / After

Before:
image

After:
image

## Test Plan

CI passes.

### CODE REVIEW

**Comment by jonathanlei** [comment]
Are the before after images reversed?

**Comment by mvadari** [comment]
> Are the before after images reversed?

No, it's supposed to be showing the issuer

**Comment by jonathanlei** [comment]
> > Are the before after images reversed?
> 
> No, it's supposed to be showing the issuer

oh got you. didn't have the context before

**Review by jonathanlei — APPROVED** [review]

**Review by pdp2121 — COMMENTED** [review]
Should we separate the currency and the issuer somehow to make it clearer (new line, different text color, etc.)?

**Comment by mvadari** [comment]
> Should we separate the currency and the issuer somehow to make it clearer (new line, different text color, etc.)?

Why? This is how we show amounts right now. Example: https://livenet.xrpl.org/transactions/A9CBA36B1130EE4CAC73F6828FD21AA71327551A81E0155C2B33EB94C01A524E

**Comment by pdp2121** [comment]
> > Should we separate the currency and the issuer somehow to make it clearer (new line, different text color, etc.)?
> 
> Why? This is how we show amounts right now. Example: https://livenet.xrpl.org/transactions/A9CBA36B1130EE4CAC73F6828FD21AA71327551A81E0155C2B33EB94C01A524E

I see.

**Review by pdp2121 — APPROVED** [review]

**Review by ckniffen — APPROVED** [review]

**Pull request merged**
