### PR TITLE
refactor: Switch nodes table to hooks and delete invalid code

### PR DESCRIPTION
**Pull request by ckniffen**
## High Level Overview of Change

`ledger_hash` was never supplied by the VHS so the most recent ledger color was always defaulting to #9ba2b0. The last ledger will now be a green link.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### TypeScript/Hooks Update

- [x] Updated files to React Hooks
- [ ] Updated files to TypeScript

## Before / After

TODO: Add Screenshots.

### CODE REVIEW

**Review by mvadari — COMMENTED** [review]
Why not also upgrade to TS while you're at it?

**Comment by ckniffen** [comment]
> Why not also upgrade to TS while you're at it?

Tried but was going to lose history.  Will do later.

**Comment by mvadari** [comment]
> > Why not also upgrade to TS while you're at it?
> 
> Tried but was going to lose history. Will do later.

Later as in in this PR, or in a separate PR? What do you mean by losing history?

**Comment by ckniffen** [comment]
> Later as in in this PR, or in a separate PR? What do you mean by losing history?

Separate PR.  It was counting it as a remove/add instead of a rename.  For example the search component refactor a lower percent of lines changed so it counted as a rename

**Review by khancode — APPROVED** [review]

**Pull request merged**
