### PR TITLE
added new env variable to switch between ws & wss

### PR DESCRIPTION
**Pull request by rashidmya**
## High Level Overview of Change
- added a new environment variable `REACT_APP_RIPPLED_SECURE` to switch between `ws/http` and `wss/https`
- if the env variable is not defined or not set to true, the default value would be false which means the connection is not secure
 

### Context of Change
#258 

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### TypeScript/Hooks Update

- [ ] Updated files to React Hooks
- [ ] Updated files to TypeScript

## Before / After
code added:
```js
  const isSecureConnection = process.env.REACT_APP_RIPPLED_SECURE === 'true' || false
  const wsConnectionProtocol = isSecureConnection ? 'wss' : 'ws'
  const wsConnectionPort = isSecureConnection ? '443' : '80'
```

- before
```js
  if (rippledHost.includes(':')) {
    wsUrls.push(`wss://${rippledHost}`)
  } else {
    wsUrls.push.apply(wsUrls, [
      `wss://${rippledHost}:${process.env.REACT_APP_RIPPLED_WS_PORT}`,
      `wss://${rippledHost}:443`,
    ])
  }
```
```js
  socket.p2pSocket = hasP2PSocket
    ? new XrplClient([
        `wss://${process.env.REACT_APP_P2P_RIPPLED_HOST}:${process.env.REACT_APP_RIPPLED_WS_PORT}`,
      ])
    : undefined
```

- after
```js
  if (rippledHost.includes(':')) {
    wsUrls.push(`${wsConnectionProtocol}://${rippledHost}`)
  } else {
    wsUrls.push.apply(wsUrls, [
      `${wsConnectionProtocol}://${rippledHost}:${process.env.REACT_APP_RIPPLED_WS_PORT}`,
      `${wsConnectionProtocol}://${rippledHost}:${wsConnectionPort}`,
    ])
  }
```
```js
  socket.p2pSocket = hasP2PSocket
    ? new XrplClient([
        `${wsConnectionProtocol}://${process.env.REACT_APP_P2P_RIPPLED_HOST}:${process.env.REACT_APP_RIPPLED_WS_PORT}`,
      ])
    : undefined
```

### CODE REVIEW

**Comment by mvadari** [comment]
I don't like the idea of having a new env variable for this - it clutters up the env vars, and we already have a lot.

**Comment by JST5000** [comment]
> I don't like the idea of having a new env variable for this - it clutters up the env vars, and we already have a lot.

To avoid that, It might be better to make the `REACT_APP_RIPPLED` and `REACT_APP_P2P_RIPPLED_HOST` include the `ws`/`wss` parts of their url instead of just the middle part. (Ex. `s.altnet.rippletest.net` -> `wss://s.altnet.rippletest.net`)

**Comment by mvadari** [comment]
> To avoid that, It might be better to make the `REACT_APP_RIPPLED` and `REACT_APP_P2P_RIPPLED_HOST` include the `ws`/`wss` parts of their url instead of just the middle part. (Ex. `s.altnet.rippletest.net` -> `wss://s.altnet.rippletest.net`)

That makes URLs really un-user-friendly for sidechains, since the `/` needs to be URL-encoded.

**Comment by ckniffen** [comment]
> > To avoid that, It might be better to make the `REACT_APP_RIPPLED` and `REACT_APP_P2P_RIPPLED_HOST` include the `ws`/`wss` parts of their url instead of just the middle part. (Ex. `s.altnet.rippletest.net` -> `wss://s.altnet.rippletest.net`)
> 
> That makes URLs really un-user-friendly for sidechains, since the `/` needs to be URL-encoded.

That could be the exception to the rule.  Sidechains already have support for optionally supplying the whole protocol

**Comment by rashidmya** [comment]
> > I don't like the idea of having a new env variable for this - it clutters up the env vars, and we already have a lot.
> 
> To avoid that, It might be better to make the `REACT_APP_RIPPLED` and `REACT_APP_P2P_RIPPLED_HOST` include the `ws`/`wss` parts of their url instead of just the middle part. (Ex. `s.altnet.rippletest.net` -> `wss://s.altnet.rippletest.net`)

should I implement this? @ckniffen

**Comment by mvadari** [comment]
> > > To avoid that, It might be better to make the `REACT_APP_RIPPLED` and `REACT_APP_P2P_RIPPLED_HOST` include the `ws`/`wss` parts of their url instead of just the middle part. (Ex. `s.altnet.rippletest.net` -> `wss://s.altnet.rippletest.net`)
> > 
> > 
> > That makes URLs really un-user-friendly for sidechains, since the `/` needs to be URL-encoded.
> 
> That could be the exception to the rule. Sidechains already have support for optionally supplying the whole protocol

That feels like a worse UX in prod, because in prod you can't use any `ws` connection due to CORS.

**Comment by intelliot** [comment]
Personally I think it's fine to include the protocol in the ENV variables, as ckniffen suggested. @mvadari thoughts?

**Comment by mvadari** [comment]
> Personally I think it's fine to include the protocol in the ENV variables, as ckniffen suggested. @mvadari thoughts?

I guess it's fine, yeah. I was hoping that we could have some sort of elegant solution where the Explorer would automatically detect if you were running locally instead of in production, and change the protocol automatically.

**Comment by ckniffen** [comment]
> I guess it's fine, yeah. I was hoping that we could have some sort of elegant solution where the Explorer would automatically detect if you were running locally instead of in production, and change the protocol automatically.

Having the full protocol will also help when pointing to a server we haven't set up SSL on yet that isn't local too. That was the case for some servers that were set up for clio nft calls for weeks.

**Comment by mvadari** [comment]
> Having the full protocol will also help when pointing to a server we haven't set up SSL on yet that isn't local too. That was the case for some servers that were set up for clio nft calls for weeks.

We can't connect to servers that don't have SSL in prod, due to CORS, since the production website is deployed on HTTPS.

**Comment by ckniffen** [comment]
> We can't connect to servers that don't have SSL in prod, due to CORS, since the production website is deployed on HTTPS.

This was doing local explorer development and pointing to a ip address for the p2p socket but using a production server over ssl for the main socket.  Normally while doing local development I am pointing to both to a production server.

**Comment by mvadari** [comment]
> > We can't connect to servers that don't have SSL in prod, due to CORS, since the production website is deployed on HTTPS.
> 
> This was doing local explorer development and pointing to a ip address for the p2p socket but using a production server over ssl for the main socket. Normally while doing local development I am pointing to both to a production server.

Sorry, I meant that I wish we could detect if the _Explorer_ is running locally, and switch to `ws` in that case.

**Comment by mvadari** [comment]
Closed in favor of #394

**Comment by mvadari** [comment]
Closed in favor of https://github.com/ripple/explorer/pull/394

**Pull request closed without merging**
