### PR TITLE
fix: EscrowCancel table detail and test warnings

### PR DESCRIPTION
**Pull request by ckniffen**
## High Level Overview of Change

- `<Trans>` warning turned out to be the component was used incorrectly and the test was inadequate
- `toHaveTagName` -> `toHaveDisplayName`
- use `createWrapper` in `<Amount>` test

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)

## Before
EscrowCancel Before

## After
EscrowCancel After

### CODE REVIEW

**Comment by JST5000** [comment]
What is that "- 9" on the end of the green text in the screenshot? (I can't figure out what it's supposed to represent from looking at it)

**Review by JST5000 — APPROVED** [review]
LGTM, just a few questions for my understanding.

**Comment by ckniffen** [comment]
> What is that "- 9" on the end of the green text in the screenshot? (I can't figure out what it's supposed to represent from looking at it)
> 
> Also nit: The space between the green text and the "- 9" seems to be absorbed / disappeared for some reason, even though it is in the code. (It looks like "...xt56- 9" instead of "...xt56 - 9")

The 9 is the sequence number of the escrow that was cancelled.  I will look into the absorbed space.

**Comment by ckniffen** [comment]
@JST5000 fixed the spacing issue.

**Review by intelliot — APPROVED** [review]

**Pull request merged**
