### PR TITLE
linting changes

### PR DESCRIPTION
**Pull request by ledhed2222**
## High Level Overview of Change

Please read commit-by-commit:

1. First commit moves our lint config directly into `package.json` and removes separate linter config files.
2. Second commit requires that we use trailing commas where possible in JS
3. Third commit autofixes based on new config.
4. Format `package.json` via `npm`, which resulted in a new package.lock

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by intelliot** [comment]
What's the benefit of using trailing commas where possible in JS?

I don't care either way, but if it makes no difference then I try to keep using whatever a majority of the project is currently using, to make diffs smaller and make things like `git blame` a little more efficient to use in the future.

**Comment by ledhed2222** [comment]
That’s exactly the rationale behind trailing commas :) If you add to a
collection at the end of it in the future, you don’t have to also editing
the line above to add a comma. I’m very very bullish on enforcing them, for
clean history moving forward

**Review by intelliot — APPROVED** [review]
LGTM

**Review by mvadari — APPROVED** [review]
why move the settings to package.json?

**Comment by ledhed2222** [comment]
@mvadari it's what newer repos do. i wanted to make changes to linting anyway so thought we should move towards this pattern while I was at it.

**Pull request merged**
