### PR TITLE
fix: remove testUtils from code coverage

### PR DESCRIPTION
**Pull request by mvadari**
## High Level Overview of Change

Title says it all.

### Context of Change

The test utils are just helpers for the tests, so we don't care about counting them in code coverage.

### Type of Change

- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)

## Test Plan

Works in CI.

### CODE REVIEW

**Comment by ckniffen** [comment]
Should these files be in src?

**Comment by mvadari** [comment]
> Should these files be in src?

Pretty sure someone asked me to put them in src (I thought it was you).

**Review by pdp2121 — APPROVED** [review]

**Comment by ckniffen** [comment]
> > Should these files be in src?
> 
> Pretty sure someone asked me to put them in src (I thought it was you).

I just asked them to be put together in a folder. https://github.com/ripple/explorer/pull/509#discussion_r1081913803

**Comment by ckniffen** [comment]
Outside of src makes sense because these are not even utils but setup how jest compiles.

**Review by ckniffen — APPROVED** [review]

**Pull request merged**
