### PR TITLE
Add metadata styling for Multi Purpose Token

### PR DESCRIPTION
**Pull request by pdp2121**
## High Level Overview of Change

MPTokenMetadata is an essential part of a MPT token as it allows issuers to define their own metadata standards, tailored to their specific requirements, encompassing details like asset codes, common names, symbols, or even visual representations.

This PR formats the display of this metadata field in the Explorer by adding json formatter for readability.

### Context of Change

Spec: https://github.com/XRPLF/XRPL-Standards/tree/master/XLS-0033d-multi-purpose-tokens

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Translation Updates
- [ ] Release

## Before / After

MPTokenIssuanceCreate Page:

Screenshot 2024-10-10 at 3 53 01 PM

MPT Page:
Screenshot 2024-10-10 at 3 53 20 PM

### CODE REVIEW

**Comment by mvadari** [comment]
Why not use `SimpleGroup` instead?

image

**Review by shawnxie999 — APPROVED** [review]
LGTM

**Review by achowdhry-ripple — APPROVED** [review]
LGTM

**Comment by pdp2121** [comment]
> Why not use `SimpleGroup` instead?
> 
> image
> 
> Or how the hook parameters are done here: image

I was thinking of this at first but since we don't have a standardized structure for metadata, the SimpleGroup might get messy (when there's nested json or array for example). Julian and I both think we can just use the Json formatter for now and revisit once the metadata structure has been defined, probably in the next couple of months. Please let me know if you think differently.

**Comment by mvadari** [comment]
> I was thinking of this at first but since we don't have a standardized structure for metadata, the SimpleGroup might get messy (when there's nested json or array for example). Julian and I both think we can just use the Json formatter for now and revisit once the metadata structure has been defined, probably in the next couple of months. Please let me know if you think differently.

That's fair - if you don't know how much it'll be nested that can get complex. Makes sense for now.

**Pull request merged**
