### PR TITLE
feat: #173 - Add GitHub link to header

### PR DESCRIPTION
**Pull request by justinr1234**
## High Level Overview of Change

- Fix alignment in header
- Add GitHub link to header (#173)
- Remove dead code
- Fix wrapping on external link icon at tablet-ish widths

### Context of Change

#173 

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### Align UI Links

**Before**
image

**After**
image

### Add GitHub Link

**Before**
image
image

**After**
image
image

### Fix external link icon wrapping on tablet-ish widths

**Before**
image

**After**
image

### CODE REVIEW

**Comment by ckniffen** [comment]
What caused the package-lock.json to change?

**Comment by ckniffen** [comment]
> > What caused the package-lock.json to change?
> 
> Not sure @ckniffen —- I installed fresh with latest version of Node 14

I think you might need to update to npm@7 or 8.  I believe the package-lock version was 2 and the one you committed is v1

**Comment by justinr1234** [comment]
Sounds good, I’ll try that and update the readme.

how do you feel about adding to the package json version for that as well as adding a nvmrc?

@ckniffen

**Comment by ckniffen** [comment]
> how do you feel about adding to the package json version for that as well as adding a nvmrc?

I am totally good with that.  Was on my list.

**Comment by justinr1234** [comment]
@ckniffen Upgrading npm to 8 worked

**Review by ckniffen — APPROVED** [review]

**Review by jonathanlei — APPROVED** [review]
LGTM

**Pull request merged**
