### PR TITLE
fix: show parsed currency code in balance

### PR DESCRIPTION
**Pull request by ckniffen**
## High Level Overview of Change

Update account balance selection to use parsed currency code.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Before
Monosnap XRPL Explorer | rsoLo2S1kiGe  2023-03-20 09-55-41

## After
Monosnap XRPL Explorer | rsoLo2S1kiGe  2023-03-20 09-54-57

### CODE REVIEW

**Comment by mvadari** [comment]
IMO this should be of the form `SOLO.rABC...` given the many different USDs and such

**Comment by lathanbritz** [comment]
> IMO this should be of the form `SOLO.rABC...` given the many different USDs and such

I like the idea, but i x characters after the token still leaves it open to overlap. One already has the full break down when selecting the assets tab. Maybe when one has selected the asset (you can click and select it) then it shows the issuer.

**Comment by ckniffen** [comment]
> IMO this should be of the form `SOLO.rABC...` given the many different USDs and such

The way it works now is these totals are a roll up of a currency regardless of issuer.  If the user wants to see the totals by issuer they can go to the assets tab.

**Review by JST5000 — APPROVED** [review]
LGTM

**Review by justinr1234 — APPROVED** [review]

**Pull request merged**
